/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.unikom.sbd8.perpustakaan;

import javax.swing.ImageIcon;

/**
 *
 * @author Rahadian Nugraha
 */
public class FormHome extends javax.swing.JFrame {

    private String namaUser;
    private String hakAksesUser;
    
    public FormHome() {
        initComponents();
    }
    public FormHome(String nama, String hakAkses) {
        initComponents();
        namaUser = nama;
        hakAksesUser = hakAkses;
        textNamaUser.setText(namaUser);
        textStatus.setText(hakAksesUser);
        if (hakAksesUser.equalsIgnoreCase("Petugas Perpustakaan")) {
            btnAnggota.setVisible(false);
            btnJenisBuku.setVisible(false);
            btnBuku.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelJudul1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAnggota = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnJenisBuku = new javax.swing.JLabel();
        btnBuku = new javax.swing.JLabel();
        btnPeminjaman = new javax.swing.JLabel();
        btnPengembalian = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JLabel();
        btnHome = new javax.swing.JLabel();
        btnHistory = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        textNamaUser = new javax.swing.JLabel();
        textStatus = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(236, 240, 241));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel3.setBackground(new java.awt.Color(189, 195, 199));

        labelJudul1.setBackground(new java.awt.Color(255, 255, 255));
        labelJudul1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelJudul1.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJudul1.setText("CV Pusat Dakwah Visual (PUSDAV)");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jl. Dipatiukur 112 Call.022-2504119 Fax. 022-2533754");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelJudul1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(labelJudul1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        btnAnggota.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnAnggota.png"))); // NOI18N
        btnAnggota.setAlignmentY(0.0F);
        btnAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnggotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAnggotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAnggotaMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SMPN 2 Bandung");

        btnJenisBuku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnJenisBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnJenisBuku.png"))); // NOI18N
        btnJenisBuku.setAlignmentY(0.0F);
        btnJenisBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJenisBukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnJenisBukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnJenisBukuMouseExited(evt);
            }
        });

        btnBuku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnBuku.png"))); // NOI18N
        btnBuku.setAlignmentY(0.0F);
        btnBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBukuMouseExited(evt);
            }
        });

        btnPeminjaman.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnPeminjaman.png"))); // NOI18N
        btnPeminjaman.setAlignmentY(0.0F);
        btnPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPeminjamanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPeminjamanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPeminjamanMouseExited(evt);
            }
        });

        btnPengembalian.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnPengembalian.png"))); // NOI18N
        btnPengembalian.setAlignmentY(0.0F);
        btnPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPengembalianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPengembalianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPengembalianMouseExited(evt);
            }
        });

        btnKeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnKeluar.png"))); // NOI18N
        btnKeluar.setAlignmentY(0.0F);
        btnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKeluarMouseExited(evt);
            }
        });

        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnHomeClick.png"))); // NOI18N
        btnHome.setAlignmentY(0.0F);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });

        btnHistory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnHistory.png"))); // NOI18N
        btnHistory.setAlignmentY(0.0F);
        btnHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHistoryMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Sistem Informasi Perpustakaan ini berfungsi untuk mengelola dan mengatur segala ");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("kegiatan-kegiatan yang ada di Perpustakaan SMPN 2 Bandung. Seperti pengolahan");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("data anggota, jenis buku, buku, peminjaman, pengembalian, dan pencetakan laporan.");

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Nama");

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Status");

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText(":");

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText(":");

        textNamaUser.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        textNamaUser.setForeground(new java.awt.Color(153, 153, 153));
        textNamaUser.setText("Nama User");

        textStatus.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        textStatus.setForeground(new java.awt.Color(153, 153, 153));
        textStatus.setText("Status User");

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Selamat datang di Sistem Informasi Perpustakaan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnggota, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnJenisBuku, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuku, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPeminjaman, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPengembalian, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHistory, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textNamaUser))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textStatus)))))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnHome))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAnggota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJenisBuku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPeminjaman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPengembalian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHistory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKeluar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnggotaMouseEntered
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnAnggotaHover.png"));
        btnAnggota.setIcon(icon);
    }//GEN-LAST:event_btnAnggotaMouseEntered

    private void btnAnggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnggotaMouseExited
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnAnggota.png"));
        btnAnggota.setIcon(icon);
    }//GEN-LAST:event_btnAnggotaMouseExited

    private void btnAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnggotaMouseClicked
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnAnggotaClick.png"));
        btnAnggota.setIcon(icon);
        dispose();
        FormAnggota fa = new FormAnggota(namaUser, hakAksesUser);
        fa.setLocationRelativeTo(null);
        fa.setVisible(true);
        
    }//GEN-LAST:event_btnAnggotaMouseClicked

    private void btnJenisBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJenisBukuMouseClicked
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnJenisBukuClick.png"));
        btnJenisBuku.setIcon(icon);
        dispose();
        FormJenisBuku fjb = new FormJenisBuku(namaUser, hakAksesUser);
        fjb.setLocationRelativeTo(null);
        fjb.setVisible(true);
    }//GEN-LAST:event_btnJenisBukuMouseClicked

    private void btnJenisBukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJenisBukuMouseEntered
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnJenisBukuHover.png"));
        btnJenisBuku.setIcon(icon);
    }//GEN-LAST:event_btnJenisBukuMouseEntered

    private void btnJenisBukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJenisBukuMouseExited
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnJenisBuku.png"));
        btnJenisBuku.setIcon(icon);
    }//GEN-LAST:event_btnJenisBukuMouseExited

    private void btnBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBukuMouseClicked
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnBukuClick.png"));
        btnBuku.setIcon(icon);
        dispose();
        FormBuku fb = new FormBuku(namaUser, hakAksesUser);
        fb.setLocationRelativeTo(null);
        fb.setVisible(true);
    }//GEN-LAST:event_btnBukuMouseClicked

    private void btnBukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBukuMouseEntered
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnBukuHover.png"));
        btnBuku.setIcon(icon);
    }//GEN-LAST:event_btnBukuMouseEntered

    private void btnBukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBukuMouseExited
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnBuku.png"));
        btnBuku.setIcon(icon);
    }//GEN-LAST:event_btnBukuMouseExited

    private void btnPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeminjamanMouseClicked
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnPeminjamanClick.png"));
        btnPeminjaman.setIcon(icon);
        dispose();
        FormPeminjaman fp = new FormPeminjaman(namaUser, hakAksesUser);
        fp.setLocationRelativeTo(null);
        fp.setVisible(true);
    }//GEN-LAST:event_btnPeminjamanMouseClicked

    private void btnPeminjamanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeminjamanMouseEntered
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnPeminjamanHover.png"));
        btnPeminjaman.setIcon(icon);
    }//GEN-LAST:event_btnPeminjamanMouseEntered

    private void btnPeminjamanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeminjamanMouseExited
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnPeminjaman.png"));
        btnPeminjaman.setIcon(icon);
    }//GEN-LAST:event_btnPeminjamanMouseExited

    private void btnPengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPengembalianMouseClicked
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnPengembalianClick.png"));
        btnPengembalian.setIcon(icon);
        dispose();
        FormPengembalian fp = new FormPengembalian(namaUser, hakAksesUser);
        fp.setLocationRelativeTo(null);
        fp.setVisible(true);
    }//GEN-LAST:event_btnPengembalianMouseClicked

    private void btnPengembalianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPengembalianMouseEntered
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnPengembalianHover.png"));
        btnPengembalian.setIcon(icon);
    }//GEN-LAST:event_btnPengembalianMouseEntered

    private void btnPengembalianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPengembalianMouseExited
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnPengembalian.png"));
        btnPengembalian.setIcon(icon);
    }//GEN-LAST:event_btnPengembalianMouseExited

    private void btnKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseClicked
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnKeluarClick.png"));
        btnKeluar.setIcon(icon);
        dispose(); 
        FormLogin fl = new FormLogin(this, true);
        fl.setLocationRelativeTo(null);
        fl.setVisible(true);
    }//GEN-LAST:event_btnKeluarMouseClicked

    private void btnKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseEntered
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnKeluarHover.png"));
        btnKeluar.setIcon(icon);
    }//GEN-LAST:event_btnKeluarMouseEntered

    private void btnKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseExited
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnKeluar.png"));
        btnKeluar.setIcon(icon);
    }//GEN-LAST:event_btnKeluarMouseExited

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked

    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered

    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
 
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryMouseClicked
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnHistoryClick.png"));
        btnHistory.setIcon(icon);
    }//GEN-LAST:event_btnHistoryMouseClicked

    private void btnHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryMouseEntered
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnHistoryHover.png"));
        btnHistory.setIcon(icon);
    }//GEN-LAST:event_btnHistoryMouseEntered

    private void btnHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryMouseExited
        ImageIcon icon = new ImageIcon(getClass().getResource("/id/ac/unikom/sbd8/perpustakaan/image/btnHistory.png"));
        btnHistory.setIcon(icon);
    }//GEN-LAST:event_btnHistoryMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHome().setVisible(true);
                new FormHome().setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAnggota;
    private javax.swing.JLabel btnBuku;
    private javax.swing.JLabel btnHistory;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnJenisBuku;
    private javax.swing.JLabel btnKeluar;
    private javax.swing.JLabel btnPeminjaman;
    private javax.swing.JLabel btnPengembalian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelJudul1;
    private javax.swing.JLabel textNamaUser;
    private javax.swing.JLabel textStatus;
    // End of variables declaration//GEN-END:variables
}
